# Copyright 2022, Atlan
---
site_name: Developer
site_description: Dear Developers
copyright: >-
  Copyright &copy; 2022 Atlan<br>Built with 💙 for the 🤖-making 🧑's of Data
#repo_name: atlanhq/atlan-customer-journey
#repo_url: https://github.com/atlanhq/atlan-customer-journey
site_url: https://reference.atlan.com
edit_uri: ""

nav:
  - Overview: index.md
  - SDKs:
    - SDKs introduction: sdks/index.md
    - Java SDK:
      - Getting started: sdks/java/getting-started.md
      - Basic operations:
        - Creating an asset: sdks/java/basic-operations/create.md
        - Retrieving an asset: sdks/java/basic-operations/read.md
        - Updating an asset: sdks/java/basic-operations/update.md
        - Deleting an asset: sdks/java/basic-operations/delete.md
        - Searching for assets: sdks/java/basic-operations/search.md
        - Error-handling: sdks/java/basic-operations/errors.md
    - Python SDK:
      - Introduction to the Atlan Python SDK: sdks/python/index.md
      - Getting started: sdks/python/getting-started.md
      - Basic operations:
        - Creating an asset: sdks/python/basic-operations/create.md
        - Retrieving an asset: sdks/python/basic-operations/read.md
        - Updating an asset: sdks/python/basic-operations/update.md
        - Deleting an asset: sdks/python/basic-operations/delete.md
        - Searching for assets: sdks/python/basic-operations/search.md
        - Error-handling: sdks/python/basic-operations/errors.md
    - Examples:
      - Certify assets: sdks/common-examples/certificates.md
      - Manage announcements: sdks/common-examples/announcements.md
      - Classify assets: sdks/common-examples/classifications.md
      - Change custom metadata: sdks/common-examples/custom-metadata.md
      - Manage lineage: sdks/common-examples/lineage.md
      - Link terms to assets: sdks/common-examples/term-assignment.md
      - Add asset READMEs: sdks/common-examples/readme.md
  - Search attributes:
    - Search attributes introduction: search/index.md
    - Common attributes: search/common.md
    - Attributes for assets: search/assets.md
    - Glossary-specific: search/glossary.md
    - Connection-specific: search/connections.md
    - SQL asset-specific: search/sql.md
    - BI asset-specific:
      - Looker-specific: search/bi/looker.md
      - Tableau-specific: search/bi/tableau.md
      - Power BI-specific: search/bi/powerbi.md
  - Key concepts:
    - Key concepts: concepts/index.md
    - Atlan objects:
      - Type definitions: concepts/typedefs.md
      - Entities: concepts/entities.md
      - Relationships: concepts/relationships.md
      - Assets: concepts/assets.md
    - Access:
      - API tokens: concepts/api-tokens.md
#  - Error codes:
#    - Else: else.md

theme:
  name: material
  language: en
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - search.highlight
    - navigation.tracking
    - content.code.annotate
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: atlan-light
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: atlan-dark
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.ico
  logo: assets/atlan-logo-blue.svg

extra_css:
  - assets/stylesheets/atlan.css

extra:
  generator: false
#  analytics:
#    provider: google
#    property: G-C0M7W5P2GZ
#  consent:
#    title: Cookie consent
#    description: >-
#      We use cookies to recognize your repeated visits and preferences, as well
#      as to measure the effectiveness of our documentation and whether users
#      find what they're searching for. With your consent, you're helping us to
#      make our documentation better 💙
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/AtlanHQ/
      name: Atlan on Facebook
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/atlan-hq/
      name: Atlan on LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AtlanHQ
      name: Atlan on Twitter

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - abbr
  - tables
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
