# SPDX-License-Identifier: Apache-2.0
# Copyright 2022 Atlan Pte. Ltd.
name: "Merge"

on:
  push:
    branches: [main]

jobs:
  merge-build:
    runs-on: ubuntu-latest
    name: "Merge"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
      - name: Check formatting
        run: ./gradlew spotlessCheck
      - name: Build artifacts
        run: ./gradlew assemble shadowJar
  publish-docs:
    runs-on: ubuntu-latest
    name: "JavaDocs"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
      - name: Publish Javadoc
        run: |
          ./gradlew gitPublishPush --stacktrace --info
        env:
          GRGIT_USER: ${{ github.actor }}
          GRGIT_PASS: ${{ secrets.GITHUB_TOKEN }}
  publish-snapshot:
    runs-on: ubuntu-latest
    name: "Snapshot"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
      - name: Configure GPG key
        run: |
          set -ex
          echo $GPG_SIGNING_PRIVKEY | base64 --decode | gpg --import --batch --yes --pinentry-mode loopback --passphrase "$GPG_SIGNING_PASSPHRASE"
        env:
          GPG_SIGNING_PRIVKEY: ${{ secrets.GPG_SIGNING_PRIVKEY }}
          GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
      - name: Publish package
        run: |
          ./gradlew publish -Dorg.gradle.project.NEXUS_USERNAME=$NEXUS_USERNAME -Dorg.gradle.project.NEXUS_PASSWORD=$NEXUS_PASSWORD -Dorg.gradle.project.signing.gnupg.keyName=$GPG_SIGNING_KEYID -Dorg.gradle.project.signing.gnupg.passphrase=$GPG_SIGNING_PASSPHRASE
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          GPG_SIGNING_KEYID: ${{ secrets.GPG_SIGNING_KEYID }}
          GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
  publish-images:
    needs: merge-build
    runs-on: ubuntu-latest
    name: "Containers"
    steps:
      - uses: docker/setup-buildx-action@v2
      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set version
        run: |
          echo "VERSION=$(./gradlew properties --no-daemon --console=plain -q | grep '^version:' | awk '{printf $2}')" >> $GITHUB_ENV
      - name: Create assembly area
        run: |
          mkdir -p ./containers/numaflow/assembly
      - name: Copy Java SDK to assembly
        run: |
          cp build/libs/atlan-java-${{ env.VERSION }}-jar-with-dependencies.jar containers/numaflow/assembly/.
      - name: Build and publish container image
        if: ${{ github.ref == 'refs/heads/main'}}
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/atlanhq/atlan-java-numaflow:${{ env.VERSION }}, ghcr.io/atlanhq/atlan-java-numaflow:latest
          context: ./containers/numaflow
          platforms: linux/amd64
