# SPDX-License-Identifier: Apache-2.0
# Copyright 2022 Atlan Pte. Ltd.
name: "Merge"

on:
  push:
    branches: [main]

jobs:
  merge-build:
    runs-on: ubuntu-latest
    name: "Merge"
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Set version
        id: get_version
        run: |
          echo "version=$(./gradlew properties --no-daemon --console=plain -q | grep '^version:' | awk '{printf $2}')" >> $GITHUB_OUTPUT
      - name: Check formatting
        run: ./gradlew spotlessCheck
      - name: Build artifacts
        run: ./gradlew assemble shadowJar buildZip
        env:
          GH_USERNAME: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: sdk
          path: sdk/build/libs/atlan-java-*-jar-with-dependencies.jar
      - uses: actions/upload-artifact@v3
        with:
          name: config
          path: package-toolkit/config/build/libs/package-toolkit-config-*-jar-with-dependencies.jar
      - uses: actions/upload-artifact@v3
        with:
          name: runtime
          path: package-toolkit/runtime/build/libs/package-toolkit-runtime-*-jar-with-dependencies.jar
      - uses: actions/upload-artifact@v3
        with:
          name: events
          path: package-toolkit/events/build/libs/package-toolkit-events-*-jar-with-dependencies.jar
      - uses: actions/upload-artifact@v3
        with:
          name: api-token-connection-admin
          path: jars/api-token-connection-admin-*.jar
      - uses: actions/upload-artifact@v3
        with:
          name: lambda-layer
          path: sdk/build/distributions/sdk-*.zip
  publish-docs:
    runs-on: ubuntu-latest
    name: "JavaDocs"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Publish Javadoc
        run: |
          ./gradlew gitPublishPush --stacktrace --info
        env:
          GH_USERNAME: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GRGIT_USER: ${{ github.actor }}
          GRGIT_PASS: ${{ secrets.GITHUB_TOKEN }}
  publish-snapshot:
    runs-on: ubuntu-latest
    name: "Snapshot"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Configure GPG key
        run: |
          set -ex
          echo $GPG_SIGNING_PRIVKEY | base64 --decode | gpg --import --batch --yes --pinentry-mode loopback --passphrase "$GPG_SIGNING_PASSPHRASE"
        env:
          GPG_SIGNING_PRIVKEY: ${{ secrets.GPG_SIGNING_PRIVKEY }}
          GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
      - name: Publish package
        run: |
          ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository -Dorg.gradle.project.sonatypeUsername=$NEXUS_USERNAME -Dorg.gradle.project.sonatypePassword=$NEXUS_PASSWORD -Dorg.gradle.project.signing.gnupg.keyName=$GPG_SIGNING_KEYID -Dorg.gradle.project.signing.gnupg.passphrase=$GPG_SIGNING_PASSPHRASE
        env:
          GH_USERNAME: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          GPG_SIGNING_KEYID: ${{ secrets.GPG_SIGNING_KEYID }}
          GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
  publish-base-image:
    needs: merge-build
    runs-on: ubuntu-latest
    name: "Base image"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create assembly area
        run: |
          mkdir -p ./containers/base/assembly
      - uses: actions/download-artifact@v3
        with:
          name: sdk
          path: ./containers/base/assembly
      - uses: actions/download-artifact@v3
        with:
          name: runtime
          path: ./containers/base/assembly
      - uses: actions/download-artifact@v3
        with:
          name: events
          path: ./containers/base/assembly
      - name: Build and publish container image
        if: ${{ github.ref == 'refs/heads/main'}}
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/atlanhq/atlan-java:${{ needs.merge-build.outputs.version }}, ghcr.io/atlanhq/atlan-java:latest
          context: ./containers/base
          platforms: linux/amd64
  api-token-connection-admin:
    needs:
      - merge-build
      - publish-base-image
    runs-on: ubuntu-latest
    name: "API token connection admin container"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create assembly area
        run: |
          mkdir -p ./containers/custom-package/assembly
      - uses: actions/download-artifact@v3
        with:
          name: api-token-connection-admin
          path: ./containers/custom-package/assembly
      - name: Build and publish container image
        if: ${{ github.ref == 'refs/heads/main'}}
        uses: docker/build-push-action@v4
        with:
          build-args: |
            VERSION=${{ needs.merge-build.outputs.version }}
            PKG_NAME=api-token-connection-admin
          push: true
          tags: ghcr.io/atlanhq/csa-api-token-connection-admin:${{ needs.merge-build.outputs.version }}, ghcr.io/atlanhq/csa-api-token-connection-admin:latest
          context: ./containers/custom-package
          platforms: linux/amd64
