# SPDX-License-Identifier: Apache-2.0
# Copyright 2022 Atlan Pte. Ltd.
name: "Test"

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  live-test:
    runs-on: ubuntu-latest
    name: "Integration"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
      - name: Integration tests
        run: ./gradlew -PintegrationTests integration-tests:test
        env:
          ATLAN_BASE_URL: ${{ secrets.ATLAN_BASE_URL }}
          ATLAN_API_KEY: ${{ secrets.ATLAN_API_KEY }}
      - if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: integration-tests/test.log
  package-test:
    runs-on: ubuntu-latest
    name: "Packages"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
      - name: Integration tests
        run: ./gradlew -PpackageTests test
        env:
          ATLAN_BASE_URL: ${{ secrets.ATLAN_BASE_URL }}
          ATLAN_API_KEY: ${{ secrets.ATLAN_API_KEY }}
      - if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: samples/packages/**/debug.log
